###

POST http://localhost:8080/posts 
Content-Type: application/json

{
"title": "The Shlomi post!", "sender": "shlomi", "content": "Posting is soooo much fun!!!"
}

###

GET http://localhost:8080/posts

###

GET http://localhost:8080/posts?sender=stavby

###

GET http://localhost:8080/posts/6740aa79f7d3b27e1b049770

###

PUT http://localhost:8080/posts/6740aa79f7d3b27e1b049770
Content-Type: application/json

{
"content": "Posting is soooo much fun!!!\nAlso I'm Stav!"
}

###

POST http://localhost:8080/comments
Content-Type: application/json

{
"sender": "yaron", "content": "hi! my first comment!", "postId": "6740bcfcaa86a22352cb55e1"
}

###

GET http://localhost:8080/comments

###

GET http://localhost:8080/comments?sender=yaron

###

GET http://localhost:8080/comments?postId=6740bcfcaa86a22352cb55e1

###

GET http://localhost:8080/comments/6740bc6daa86a22352cb55dd

###

PUT http://localhost:8080/comments/6740bc6daa86a22352cb55dd
Content-Type: application/json

{
"content": "maybe this is my second comment?"
}

###

DELETE http://localhost:8080/comments/6740bc6daa86a22352cb55dd

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"username": "shlomi", "password": "secretpassword123", "email": "shlomi@gmail.com"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"username": "shlomi", "password": "secretpassword123"
}

###

POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoicmVmcmVzaCIsInVzZXJJZCI6IjY3NzFjYWJkMzI5ZGZkMjdmZmQ1OTNmYSIsInJhbmRvbSI6IjE3M2I1ZjExY2E4MmY1MzRiNGMyOGU1NTAyNGJhZDdmMzk0ZWFjODQ3NGM5ODM0MWQ4Yjk3NWUyZGZiYzg3OTk1N2RlNjg5OGZlZGQ2Yzk4OWNiNDI1ZTBhZmIyOTExZjc0ZDI4ZjgzOTEwMTgxNDQ4Mzc1ODYyZGViZmYyNGY5IiwiaWF0IjoxNzM1NTExNDQxLCJleHAiOjE3MzU1OTc4NDF9.tnkEGz37xpkt3o2YdQYTTwTaGsTCf45j_9jYPTSrxQc"
}

###

GET http://localhost:8080/users?username=shlomi
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwidXNlcklkIjoiNjc3MWNhYmQzMjlkZmQyN2ZmZDU5M2ZhIiwicmFuZG9tIjoiNGE5MTBhN2ZmMDM4NzhkZDc2OTk2MGUzNTY5NDgxOGI0ZTMxNTE5ZTBmM2IxN2VjYWQwOWMyZDkxYWM5N2FlYzE5ZTMzZDlhMzg3ZTBlNDMzZjZlZjg3NWRhYTQwYmZiMzIzNTJiMzkzNWI2MjQ5MzMwOWYwMzQyNTMyZjlhZmMiLCJpYXQiOjE3MzU1MTI0MDQsImV4cCI6MTczNTUxNjAwNH0.FxtBS6duLDCrdkdtJ79nvaXdzBtbNY-_rz10O_IY2XI

###

GET http://localhost:8080/users?email=shlomi@gmail.com


###

GET http://localhost:8080/users?userId=676fe19ab96f197a6f3ec8d1

###

PUT http://localhost:8080/users/676fe19ab96f197a6f3ec8d1
Content-Type: application/json

{
"email": "shlominew@gmail.com"
}

###

DELETE http://localhost:8080/users/676fe19ab96f197a6f3ec8d1
